name: Benchmark

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 2.7
          - pypy2
          - 3.8
          - pypy3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      # - name: Install enum34
      #   run: python -m pip install enum34
      #   if: ${{ matrix.python-version == 2.7 || matrix.python-version == 'pypy2' }}
      - name: Install statistics
        run: python -m pip install statistics
        if: ${{ matrix.python-version == 2.7 || matrix.python-version == 'pypy2' }}
      - name: Install KS runtime library
        run: python -m pip install kaitaistruct
      - name: Generate sample.bin
        run: python generate_sample.py
      - name: Run benchmark
        run: python index.py
